### ISSUE TITLE
[Community feedback] What Theme/skin are you using?

### ISSUE THREAD

**Issue by LiorBanai** [Analogy-LogViewer/Analogy.LogViewer#515]
Question is self explanatory :) 
Are you using White/Dark mode? other theme/skin?
![image](https://user-images.githubusercontent.com/36262995/94139050-b171b480-fe71-11ea-8935-b1c70e53e255.png)

![image](https://user-images.githubusercontent.com/36262995/94139429-483e7100-fe72-11ea-9de9-bd80e0f7f4fc.png)

**Comment by vocko** [comment]
Haha, until now I did not even know there are some themes. Went through them and **Office 2010 Silver** and **Blue** are my favourites (easy on eyes). I'm not a fan of a dark modes, mainly because not everything supports them and thus my monitors are permanently set to low brightness and my apps use light themes.

**Comment by LiorBanai** [comment]
I agree about dark theme. Not sure what it is so popular (except for battery power consumption)

**Comment by LiorBanai** [comment]
moving to discussion tab: https://github.com/Analogy-LogViewer/Analogy.LogViewer/discussions/763
